export const defaultSocialMediaOptions = [
  { label: 'Facebook', value: 'facebook', key: 'facebook' },
  { label: 'Instagram', value: 'instagram', key: 'instagram' },
  { label: 'Telegram', value: 'telegram', key: 'telegram' },
  { label: 'Youtube', value: 'youtube', key: 'youtube' },
  { label: 'LinkedIn', value: 'linkedin', key: 'linkedin' },
  { label: 'Snapchat', value: 'snapchat', key: 'snapchat' },
  { label: 'WeChat', value: 'wechat', key: 'wechat' },
  { label: 'WhatsApp', value: 'whatsapp', key: 'whatsapp' },
  { label: 'Twitch', value: 'twitch', key: 'twitch' },
  { label: 'Discord', value: 'discord', key: 'discord' },
  { label: 'Pinterest', value: 'pinterest', key: 'pinterest' },
  { label: 'Steam', value: 'steam', key: 'steam' },
  { label: 'Spotify', value: 'spotify', key: 'spotify' },
  { label: 'Reddit', value: 'reddit', key: 'reddit' },
  { label: 'Skype', value: 'skype', key: 'skype' },
  { label: 'Twitter', value: 'twitter', key: 'twitter' },
  { label: 'Web Site', value: 'web-site', key: 'web-site' },
];
